repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1  
    hooks:
      # Lint + auto-fix (includes import sorting, unused imports, etc.)
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        # If you don't want to run on notebooks, uncomment:
        # types_or: [python, pyi]
      # Formatter (Black-compatible)


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2 
    hooks:
      - id: mypy
        files: ^bitcoin_qr_tools/[^/]+\.py$  
        args: 
          - --follow-imports=skip
          - --check-untyped-defs
          # - --disallow-untyped-defs
          # - --disallow-incomplete-defs
          # - --strict-optional
          - --implicit-optional
          - --strict-equality
          # - --warn-return-any
          - --warn-redundant-casts
          - --warn-unreachable
          # - --disallow-any-generics           
          # - --strict        
          - --install-types
          - --non-interactive   
          - --ignore-missing-imports
          - --show-error-codes 
        language: python  # Required for additional_dependencies https://docs.renovatebot.com/modules/manager/pre-commit/
        additional_dependencies: 
          - types-requests
          - pyqt6 
          - bdkpython==1.2.0


  # - repo: local
  #   hooks:
  #     - id: pyright
  #       name: Pyright Type Check
  #       entry: pyright
  #       language: system
  #       files: ^bitcoin_qr_tools/[^/]+\.py$  
  #       types: [python]
  #       pass_filenames: true
